package rafradek.TF2weapons.client.model;

// Date: 06.01.2016 15:27:35
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSyringe extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;

	public ModelSyringe() {
		textureWidth = 32;
		textureHeight = 32;

		Shape1 = new ModelRenderer(this, 0, 6);
		Shape1.addBox(0F, 0F, 1F, 1, 1, 5);
		Shape1.setRotationPoint(0F, 0F, 0F);
		Shape1.setTextureSize(32, 32);
		Shape1.mirror = true;
		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(-1F, -1F, 0F, 3, 3, 1);
		Shape2.setRotationPoint(0F, 0F, 0F);
		Shape2.setTextureSize(32, 32);
		Shape2.mirror = true;
		Shape3 = new ModelRenderer(this, 8, 0);
		Shape3.addBox(-0.5F, -0.5F, -3F, 2, 2, 3);
		Shape3.setRotationPoint(0F, 0F, 0F);
		Shape3.setTextureSize(32, 32);
		Shape3.mirror = true;
		Shape4 = new ModelRenderer(this, 0, 0);
		Shape4.addBox(-1F, -1F, -4F, 3, 3, 1);
		Shape4.setRotationPoint(0F, 0F, 0F);
		Shape4.setTextureSize(32, 32);
		Shape4.mirror = true;
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
	}

}
